### ISSUE TITLE
Resolve nvim-compe input lag on large file?

### ISSUE THREAD

**Issue by vpeopleonatank** [kuznetsss/nvim_lua_config#1]
I saw your issue on nvim-compe about this problem. Do you have some workaround to solve It?

**Comment by kuznetsss** [comment]
I turned off treesitter from completion sources.
https://github.com/kuznetsss/nvim_lua_config/blob/master/lua/plugins/install.lua#L23

**Comment by vpeopleonatank** [comment]
Thank you
